### ISSUE TITLE
Latex: No spell checking within escaped $

### ISSUE THREAD

**Issue by jgoeders** [streetsidesoftware/cspell-dicts#1083]
In the sample .tex code below, the first and third instance of *dolllar* is identified as incorrectly spelling.  However, when you have any text between `$` symbols it is not checked.  

```
dolllar 

Spelling checks between escaped \$1,000 dolllar symbols do not work \$1,000. 

dolllar 
```

Normally between `$` symbols is math mode and it would be correct to not spell check; however, in this case the symbols are escaped and I am actually trying to use the $ (dollar) symbol in my document.  

Currently nearly my entire large .tex document is not spell checked because I have a $ symbol near the beginning and near the end.

**Comment by Jason3S** [comment]
@jgoeders,

This is really an issue with how the exclusions are defined in the LaTeX dictionary settings.

**Comment by Jason3S** [comment]
@jgoeders,

It might be a few days before this is fixed in the VS Code extension.

In the mean time, you can redefine the pattern locally:

## VS Code Settings

<img width="475" alt="image" src="https://user-images.githubusercontent.com/3740137/168414035-9d1b4d32-d8fe-46fe-a6e5-57f34ee1e4b6.png">

```json
"cSpell.languageSettings": [
    {
        "languageId": "latex",
        "patterns": [
            {
                "name": "LaTexMath",
                "pattern": "/(?<!\\\\)[$][^$]*[$]/g",
                "description": "Match against LaTex Math Macros"
            }
        ]
    }
]
```

## `cspell.json`

You could also add the following `cspell.json` file to your project.

```json
{
"languageSettings": [
    {
        "languageId": "latex",
        "patterns": [
            {
                "name": "LaTexMath",
                "pattern": "/(?<!\\\\)[$][^$]*[$]/g",
                "description": "Match against LaTex Math Macros"
            }
        ]
    }
]
}
```
