### ISSUE TITLE
LaTeX: simple math formula confuses spell checker

### ISSUE THREAD

**Issue by ari-wwu** [streetsidesoftware/cspell-dicts#1097]
The second `wxyz` is not marked as "wrong" by spell checker (false negative) in the following latex snippet:

```
wxyz

$p^1_1\in[0,2)$

wxyz
```

Surprisingly, removing the backslash `\` out of the math formula (`$p^1_1in[0,2)$`) or adding a closing `]` to the end of the formula (`$p^1_1in[0,2)]$`) leads to the expected behavior that both `wxyz` are marked by spell checker as "wrong".

**Comment by Jason3S** [comment]
@ari-wwu,

I'm not able to reproduce this issue.
<img width="220" alt="image" src="https://user-images.githubusercontent.com/3740137/169082105-db84a043-3264-41f1-b855-408b2f8b1b4d.png">

Would you please attach a copy of any `ignoreRegExpList` settings? It is most likely one of them.

**Comment by ari-wwu** [comment]
Hi @Jason3S ,

<img width="496" alt="Screenshot 2022-05-18 at 17 40 24" src="https://user-images.githubusercontent.com/24634030/169084957-21e66a6d-3991-4089-be98-c05c551db662.png">

you mean this?

**Comment by Jason3S** [comment]
@ari-wwu,

Thank you.

What patterns do you have defined in `Patterns`?

They might be overwriting the patterns used.

**Comment by Jason3S** [comment]
@ari-wwu,

Do you have any `cspell` configuration files in your project?

The issue is with a regular expression, the question is which one.

There is something else to try:
1. Enable  `cspell experimental Regexp View`
   <img width="574" alt="image" src="https://user-images.githubusercontent.com/3740137/169109410-3dc789f5-e939-41fe-9746-367a361d7d74.png">
1. Open the View:
   <img width="41" alt="image" src="https://user-images.githubusercontent.com/3740137/169110827-7bc801d8-132b-4d91-8d89-f51fc18469ac.png">
1. You will see a list like this:
   <img width="306" alt="image" src="https://user-images.githubusercontent.com/3740137/169110988-adaa66e9-677f-4ace-ac4f-a52140a67193.png">
1. If you click on them, it should highlight any matches. The ones with `(0)` do not match anything in the document. `(1)` have 1 match:
   <img width="559" alt="image" src="https://user-images.githubusercontent.com/3740137/169111520-73317fd3-d6b0-4862-a9bb-3cac0e5c6f65.png">

Please try out the ones with `(1)` and see which one highlights too much.

**Comment by Jason3S** [comment]
@ari-wwu,

That is strange. Which version of VS Code are you using? Would you copy the `About Visual Studio Code` here?

**Comment by ari-wwu** [comment]
@Jason3S 

Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.3.0

**Comment by Jason3S** [comment]
@ari-wwu,

Is there a `]` in the lines below?

<img width="265" alt="image" src="https://user-images.githubusercontent.com/3740137/169249037-dc88b9ac-d727-404d-9972-dba97a3ed94d.png">

Here is a workaround:

```jsonc
    "cSpell.languageSettings": [
        {
            "languageId": "latex",
            "patterns": [
                {
                    "name": "LaTexMacrosMultiLine",
                    "pattern": "/(?<!\\\\)\\\\(?!(?:title|color|section|subsection|footnote|chapter|part|caption|emph|enquote|text|in\\b))\\w+(?:\\[[^]*?\\]|\\{[^]*?\\})*/gi",
                    "description": "Match against multi-line LaTex Macros"
                }
            ]
        }
    ],
```

It will redefine the `LaTexMacrosMultiLine` pattern to ignore `\in`

**Comment by ari-wwu** [comment]
There is no(!) `]` in the lines below. The `[0,2)` is the standard math notation for the half-open interval of values from `0` (including) to `2` (excluding).

The workaround works -- great :-) I am just wondering why your spell checker works as expected, without your suggested workaround.
