### ISSUE TITLE
Node vs. TypeScript vs. JavaScript dictionary

### ISSUE THREAD

**Issue by nschonni** [streetsidesoftware/cspell-dicts#1411]
I believe currently the TypeScript dictionary is used when JavaScript is indicated, but since it's a superset, there are words in there that don't actually belong for plain javascript. I think that dictionary was generated off of the language repo at one point.
Similarly, Node should have a core of JavaScript words, plus the Node specific API terms.

Just raising this as I was trying to figure out where to put some terms from the https://github.com/mdn/browser-compat-data. Ideally, they'd be added to a plain "JavaScript" dictionary, that those other 2 would build on top of.

**Comment by Jason3S** [comment]
@nschonni,

Thank you for adding the words.

I can see the confusion. It does seems a bit strange to need to add JavaScript terms to the TypeScript dictionary.

I didn't see a need to have separate TypeScript and JavaScript dictionaries since TypeScript (from a keyword perspective) is a very slight superset of JavaScript. Maybe I should have called it a JavaScript dictionary. I'm hard pressed to come up with any TypeScript only keywords other than `type`.

The "fullstack" dictionary also makes things confusing. It really should be a collection of dictionaries.

I have been thinking about adding aliasing and dictionary collections to CSpell. A dictionary collection allows you to give a single name to a group of dictionaries. (An alias is a collection with just one dictionary listed). Given that, the TypeScript dictionary would just become an alias of the JavaScript dictionary, maintaining compatibility configurations that explicitly use the `typescript` dictionary. 

It is not easy to "rename" dictionaries, because it breaks existing configuration, but using aliases can help with make dictionary names consistent. Then we could fix the `en_us` / `en-gb` inconsistency.
<img width="135" alt="image" src="https://user-images.githubusercontent.com/3740137/187129751-c06a09d7-d8a8-41dd-9804-89a7e24c650a.png">
