### ISSUE TITLE
English Australian Dictionary

### ISSUE THREAD

**Issue by tw3lveparsecs** [streetsidesoftware/cspell-dicts#1537]
Can we have an English - Australian dictionary added please?

**Comment by vikivivi** [comment]
@Jason3S How about using `aoo-mozilla-en-dict` 'en_AU (Kevin Atkinson)' BSD/MIT-Like as a starting point ?

**Comment by Maxim-Mazurok** [comment]
Isn't it here already? https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/en_AU

**Comment by vikivivi** [comment]
> Isn't it here already? https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/en_AU

First commit of dictionaries/en_AU is **24 Feb 2023**.
Issue raised **25 Oct 2022**. Since this issue is already addressed 1 month ago. I guess we can close it now. 

$ git log --diff-filter=A -- dictionaries/en_AU/
commit 036b15f288239214be6c87170b27dc1ededdfcb1
Author: Jason Dent <Jason3S@users.noreply.github.com>
Date:   Fri Feb 24 17:08:54 2023 +0100

    feat: Add Australian English Dictionary (#1956)

**Comment by Jason3S** [comment]
I forget to close this issue. It has been completed.
