### ISSUE TITLE
Russian dictionary errors

### ISSUE THREAD

**Issue by iandreyshev** [streetsidesoftware/cspell-dicts#17]
Cspell marked these words as incorrect, although they are correct:
Средняя, страницу, базовая, успеха, информационная, требующая, внимания, основная, использовании, разработчика, потребуется, классы, помощью, типов, кнопки, Демонстрация

**Comment by Jason3S** [comment]
@iandreyshev,

Thank you. I am assuming that other Russian words are considered correct.
What happens if you restart VS Code? 

I was able to get it to work:
![image](https://user-images.githubusercontent.com/3740137/32952041-2bce5a4c-cb69-11e7-86ab-78deeac0efbf.png)

It is very possible that something else is causing an issue.

**Comment by Jason3S** [comment]
@iandreyshev,

I assumed you were using VS Code, that might not be the case.

For the Russian extension in VS Code, I used both Russian dictionaries in this repository, because I found neither one had enough word coverage. I have not had the time to figure out why the larger dictionary didn't not have what seemed to be common words.

Since I don't read Russian, I had used Russian newspaper sample to test the VS Code Russian extension.

If you can suggest a better open source Russian Hunspell dictionary, that would be very helpful.

**Comment by iandreyshev** [comment]
@Jason3S,

Our team uses cspell module, to run cspell we using grunt-shell.
Cspell config file:
`{
	"version": "0.1",
	"language": "en",
	"dictionaries": ["russian"],
	"import": ["./node_modules/cspell-dict-russian/cspell-ext.json"],
	"words": [
		"keyframes",
		"nowrap",
		"emsp",
		"разработчику",
		"страницу",
		"базовая",
		"Средняя",
		"дефолтная",
		"успеха",
		"информационная",
		"требующая",
		"внимания",
		"ссылочная",
		"основная",
		"использовании",
		"разработчика",
		"потребуется",
		"классы",
		"помощью",
		"типов",
		"кнопки",
		"Демонстрация"
	],
	"ignorePaths": [
		"src/img/*"
	]
}
`

**Comment by Jason3S** [comment]
Can you try adding the other Russian dictionary as well:

```
npm install -SD cspell-dict-ru-ru
```

**cspell.config.json:**
```
{
	"version": "0.1",
	"language": "ru,en",
	"dictionaries": [],
	"import": [
		"./node_modules/cspell-dict-russian/cspell-ext.json",
		"./node_modules/cspell-dict-ru-ru/cspell-ext.json"
	],
	"words": [
	],
	"ignorePaths": [
		"src/img/*"
	]
}
```

**Comment by iandreyshev** [comment]
Nice, now it`s work! Thanks!
_But I think that in the import line 2 need to use "ru_ru"_

**Comment by iandreyshev** [comment]
@Jason3S 
Can you combine this dicts and post result ?

**Comment by Jason3S** [comment]
I do plan on combining the dictionaries.

**Comment by Jason3S** [comment]
@iandreyshev The dictionaries have been combined into cspell-dict-ru_ru.
