### ISSUE TITLE
I have created a new dictionary, for the Basque Locale Language, how to add it

### ISSUE THREAD

**Issue by jmigartua** [streetsidesoftware/cspell-dicts#1703]
Hi there,

I have created a new dictionary for the Basque Language, following the steps here: https://github.com/streetsidesoftware/cspell-dicts, section: **How to Create a New Dictionary**
I think I have done it correctly...
I would like to know if it would be possible to include it in the List of Language Dictionaries.

Thank you very much

Josu

PD: I think I have done is correctly, as the generating program has shown no issue; but the point is that I can not make it work in Cspell extension in VSCode

**Comment by Jason3S** [comment]
@jmigartua,

Please make a pull request to add it here.

**Comment by Jason3S** [comment]
@jmigartua,

Did you figure it out?

**Comment by jmigartua** [comment]
I did not succeed, I am sorry, it was a *false alarm*...

In this [link](https://github.com/jmigartua/basque_hunspell) can be found the source files. `.dic` and `.aff` for the Basque Language.

Thank you for everything.

**Comment by Jason3S** [comment]
@jmigartua,

In PR #1775 I created a limited version of the dictionary. I'll increase the size a bit later today.

The issues is that Basque has a LOT of suffixes, over 100k. At the moment, I generated the dictionary by adding only 1 level of suffixes. This resulted in 3.7 million words. I'll try to generate 2 levels. When I have time to let it run for a bit.

**Comment by Jason3S** [comment]
@jmigartua,

I'll publish the dictionary with 3.7 million words. It will take more work to generate the next level.

**Comment by Jason3S** [comment]
@jmigartua,

I have published the dictionary to VS Code Marketplace: [Basque Extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-basque).

Please try it out.

Key areas to pay attention to:
1. Suggestions -- The suggestions are generated based upon common Latin sound substitutions, but these are not always the best. 
2. Missing Common Words -- Because I was only able to generate a single level of substitution, it is possible that common spellings are still missing. Adding new rules would help with this.

## Improving Suggestions

The spell checker uses a weighted edit distance calculation to derive the list of suggestions.

The list presented to the user are the ones with the lowest cost.

The basic cost of substituting one letter for another is 100. Letters not in the alphabet are slightly more expensive.

To improve suggestions, it is necessary to tell the spell checker a few things:
1. The Locale - this is used for adding / removing accents and capitalization.
2. The letters of the alphabet.
3. The suggested edit costs.

### Edit costs

In English, Great and Grateful both have the `ate` sound. But if someone misspelled Grateful as `Greatful`, the edit cost is 200 -- remove the `e` before `a` (100) and add it back after `t` (100). Since this is a common type of mistake in English, we might want to make the substitution cheaper so it appears higher in the list.

```yaml
map: (eat)(ate)
replace: 75
```

**Before**

`cspell suggest greatful -v`

<img width="283" alt="image" src="https://user-images.githubusercontent.com/3740137/212286136-98093f0e-497d-4507-8f31-97ae3bb2aa8c.png">

**After**

`cspell suggest greatful -v -d en_us`

<img width="232" alt="image" src="https://user-images.githubusercontent.com/3740137/212286776-4186e0ca-9ef2-4e6e-9b3b-181246855729.png">


Example of the [Dutch Substitution Costs](https://github.com/streetsidesoftware/cspell-dicts/blob/70ac688381f36f62b7ea631720272cf404b4bc9e/dictionaries/nl_NL/cspell-ext.json#L12-L38)

```json
"dictionaryInformation": {
    "locale": "nl-NL",
    "alphabet": "a-zA-Zëqïéèöêüçàûîñäô",
    "suggestionEditCosts": [
        {
            "map": "o(oo)|e(ee)|u(uu)|a(aa)|(ei)(ie)|(ou)(ui)|(ei)(ij)(ĳ)",
            "replace": 50
        },
        {
            "map": "s(ss)|e(en)|n(nen)",
            "replace": 75
        },
        {
            "map": "eéèëê|aáà|iíìïî|oóòöô|uüúùû|(ij)(ĳ)(IJ)(Ĳ)",
            "replace": 1
        },
        {
            "map": "(er)(ër)|(kju)(cue)|(oren)(oors)|(eck)(eque)|(ore)(oire)|(oor)(oir)|ü(ue)",
            "replace": 75
        },
        {
            "map": "(en)(nen)(s)",
            "description": "Words are compounded in plural form",
            "insDel": 90
        }
    ]
}
```

The docs are a bit lacking, you here is a good place to start: 
- [DictionaryInformation](https://cspell.org/types/cspell-types/interfaces/DictionaryInformation/)
- [Suggestion Cost Map](https://cspell.org/types/cspell-types/modules/#suggestioncostmapdef)

**Comment by Jason3S** [comment]
I'm going to close this for now.

**Comment by jmigartua** [comment]
Hi Jason,

I am using cspell all the time!! Thanks!!

I am having some "problems", so to say: I am including a lot of good words
in Basque into the user settings, via a QuickFix, they are not caught by
the spellchecker.
Perhaps, this has to do with the 2. key area to pay attention to, as you
mentioned previously.
It is not very easy to me to propose possible changes to improve the
suggestions, as I do not understand that: I mean, can not figure out which
would be the possible changes.

Josu



_______________________________________________________


    Dr. Josu M. Igartua Aldamiz
    Fisika Saila
    Zientzia eta Teknologia Fakultatea
    644 PK Bilbao 48080
    Spain

    ***@***.*** ***@***.***>
    Tfn: +34 94 601 5335
    Fax: +34 94 601 3500


ᐧ

**Comment by Jason3S** [comment]
@jmigartua,

I'm sorry about not getting back to you sooner. This one fell off my radar. I'll send you an email.
