### ISSUE TITLE
support "crafter" as a word

### ISSUE THREAD

**Issue by mfulton26** [streetsidesoftware/cspell-dicts#2430]
VSCode extension is flagging "crafter" as not a word for me but it seems to me that it is. It appears to be a valid word to play in Scrabble too. 😄 

https://scrabble.merriam.com/finder/crafter

**Comment by Jason3S** [comment]
@mfulton26,

Thank you. I think it is a word too. 

Strangely, because I'm not in the US, I cannot open that URL. It redirects me to scrabble.com.

Please add `crafter` to this file: [shared-additional-words.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_shared/src/shared-additional-words.txt) and make a pull request. That way you get credit for adding it.
