### ISSUE TITLE
"Add" codespell dictionary?

### ISSUE THREAD

**Issue by yarikoptic** [streetsidesoftware/cspell-dicts#2927]
There is a similar project https://github.com/codespell-project/codespell and it seems (https://github.com/mermaid-js/mermaid/pull/5176/files) possibly to contain some typos which are not caught by `cspell`. There are some other projects which already use codespell's dictionary to expand their coverage (don't remember from top of my head).

Thus, instead of proposing PR to add specific words here, decided to file this issue instead.

**Comment by Jason3S** [comment]
@yarikoptic,

CSpell picks up the same issues as codespell. It seems to be a configuration issue.

All the issues that codespell picks up and cspell does not are due to the patterns:

https://github.com/mermaid-js/mermaid/blob/dc857f804e955484b2f92cefc0aaa7b4afb159c4/cSpell.json#L166-L201

Please note, the patterns are applied to ALL document types and not just markdown.

**Comment by yarikoptic** [comment]
> CSpell picks up the same issues as codespell.

I am not doubting you, just wondered *how* if there is no mentioning of `codespell` anywhere in this repo and `codespell` (and I thought cspell as well) operates on a collection of typos and fixes to them, e.g.:
https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt

so, unless the same dictionary is used, CSpell would not pick up the same issues as codespell, or what am I missing?

**Comment by Jason3S** [comment]
@yarikoptic,

CSpell and `codespell` work in two different ways. `codespell` looks for common mistakes and ignores nearly everything else. 

CSpell checks all the words against the dictionaries and notifies about any that are not found. CSpell can be much noisier than `codespell`, because CSpell would flag variables like `thisisalongvariablename` while `codespell` would just ignore it.

Like `codespell`, CSpell already has a list of common misspellings:
- https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en-common-misspellings/dict-en.yaml
- https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en-common-misspellings/dict-en-gb.yaml
- https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en-common-misspellings/dict-en-us.yaml

Sourced from https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings

I believe `codespell` got its list from the same place.

If you think there are words missing, please feel free to add them, PRs are welcome. So far, I haven't seen any issues that `codespell` picks up while CSpell does not.

**Comment by yarikoptic** [comment]
THANK YOU for all the details!  I will close this issue to no clutter (feel welcome to reopen if you feel it is worth keeping afloat).
Just last note: as you have mentioned that principles of work of the two are different.  There is a number of misspellings which were added to codespell's dictionary probably beyond that wiki list: I might later check on what is missing. codespell also has https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_rare.txt which is at large - typos which are in reality are valid words but too domain specific or rare (e.g. random choice from there - `singe`) and thus are likely to be a typo.  So indeed principle of work is different since I guess cspell would never include those.
