### ISSUE TITLE
revalidates is not recognized (revalidate is recognized)

### ISSUE THREAD

**Issue by ADTC** [streetsidesoftware/cspell-dicts#2958]
As per title: `revalidates` is not recognized (`revalidate` is recognized).

**Comment by ADTC** [comment]
@Jason3S Thanks for this transfer. I keep forgetting you have a separate repo for this. May I suggest adding adequate warnings in the main repo? I can open a PR for you.

**Comment by Jason3S** [comment]
@ADTC,

Thank you. A PR is most welcome.

Please add it here: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_shared/src/shared-additional-words.txt

**Comment by ADTC** [comment]
@Jason3S haha I meant a PR for adding more warnings in the main repo. But yes, can also do a PR here to add the word.

BTW, in the main repo, it shows **two** bug report templates. One is a plain text box and the other has a form. Which one should we keep?

**Comment by Jason3S** [comment]
> @Jason3S haha I meant a PR for adding more warnings in the main repo. But yes, can also do a PR here to add the word.
> 
> BTW, in the main repo, it shows **two** bug report templates. One is a plain text box and the other has a form. Which one should we keep?

A PR in the `cspell` repo would be great.
There are **two* bug report templates because neither solution was ideal. My goal was to make it easy to fill out a casual report while still collecting enough information to reproduce the issue. It has been a while since I wrote the template, so maybe GitHub has improved them since then.
