### ISSUE TITLE
Minify PR template text

### ISSUE THREAD

**Issue by spotlesscoder** [streetsidesoftware/cspell-dicts#3630]
Is it really necessary to ask for these things?

```
Dictionary: _dictionary_

Description
description of change
```

The dictionary can be determined from the changed file path
The description should be in the commit message

**Comment by spotlesscoder** [comment]
@Jason3S what do you think

**Comment by Jason3S** [comment]
@spotlesscoder,

Good question. The template can be annoying at times.

> The dictionary can be determined from the changed file path

It is useful to know what dictionary / dictionaries they are trying to update and why. Most of the times I approve the PR from my phone and the file path is not immediately apparent. 

> The description should be in the commit message

I'm trying to avoid having to guess what the contributor has intended. They do not always add useful information to the commit message. Most of the time the commit message is just the name of the file.

In any case, I won't block a PR because the template is not fully filled in.

**Comment by spotlesscoder** [comment]
Maybe the affected dictionaries can be added in a comment by a bot running on a PR?
