### ISSUE TITLE
Add words

### ISSUE THREAD

**Issue by jim-hays-root** [streetsidesoftware/cspell-dicts#508]
Below are some suggested words to add to dictionaries.  Some might fit well in multiple dictionaries, but I've only listed each term once.

en-gb 
```
amphitheatre
```

en_us
```
centauri
christoph
covid
eligibilities
hmmm
ipads
reenable
reenabled
reenables
reenqueue
reenqueued
rerender
rerendered
rerendering
rerenders
uneditable
unintuitive
unpause
unpaused
```

companies 
```
appetize
bitly
experian
figma
hipercard
jfrog
linkedin
lyft
nordvpn
paylocity
zillow
```

fullstack
```
nullif
objectid
```

python
```
numpy
```

softwareTerms
```
architected
associable
coord
crashlytics
ddos
debouncing
deprovisioned
deprovisioning
enqueuer
enqueues
icloud
jetifier
unmounting
unmounts
unpend
unpended
```

**Comment by Jason3S** [comment]
@jim-hays-root,

Thank you for your suggestions. Please feel free to make a pull request for each of the dictionaries.

No need to fork this repository, it can be done by just editing the file directly on GitHub. The Python dictionary is found here: [dictionaries/python/python.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/python/python.txt).

Special note about the English dictionaries. Since these are more widely applied, the idea is to keep them clean. Most of the terms listed above to be added to en_US might be better suited to be added to software terms since they are primarily used with respect to software. For example, `reenable` is not yet accepted as an alternative to `re-enable`. It is trending in that direction. But, since most programming languages do not allow `-` when naming variables and functions, most developers tend to leave out the hyphen. I created an issue: [Make hyphens optional in case insensitive mode · Issue #1418 · streetsidesoftware/cspell](https://github.com/streetsidesoftware/cspell/issues/1418) to address the programming issue.

**Comment by jim-hays-root** [comment]
companies: https://github.com/streetsidesoftware/cspell-dicts/pull/510

**Comment by jim-hays-root** [comment]
python: https://github.com/streetsidesoftware/cspell-dicts/pull/511

**Comment by jim-hays-root** [comment]
en_US: https://github.com/streetsidesoftware/cspell-dicts/pull/512

**Comment by jim-hays-root** [comment]
softwareTerms: https://github.com/streetsidesoftware/cspell-dicts/pull/513

**Comment by jim-hays-root** [comment]
en_GB: https://github.com/streetsidesoftware/cspell-dicts/pull/514

**Comment by Jason3S** [comment]
@jim-hays-root,

Thank you very much.
