### ISSUE TITLE
What should/does the cpp dictionary contain

### ISSUE THREAD

**Issue by nschonni** [streetsidesoftware/cspell-dicts#54]
I was looking to see if I could clean up the cpp dictionary since i've hit a few questions. It looks like it was probably sourced from some header files for some different things (EX: found that a chunk was from the CUPS printer header files).
I'm wondering what should be in here?
- CPP keywords
- standard library headers
- other headers

I'll submit some PRs for some things, but I was wondering if these should get split into separate files, then rejoined at the compile time.

**Comment by d2s** [comment]
Makes sense to split the dictionary to smaller parts. Would it be a good idea to have more specific subsets as a separate dictionaries, so that potential users could only load those sets that they most likely need?

**Comment by Jason3S** [comment]
Please feel free to clean it up. The original was sourced from XCode header files.

**Comment by Jason3S** [comment]
To have better support for compound words and checking case, version 5 of the spell checker will support a simple dictionary definition syntax: [cspell/wordlists.md at master · streetsidesoftware/cspell](https://github.com/streetsidesoftware/cspell/blob/master/packages/cspell-tools/wordlists.md)

I want to turn of `allowCompoundWords` for the C/C++ and Python dictionaries since it leads to a lot of false negatives (meaning it allows strange misspelled words).

So, what should be in the cpp dictionary?
* Common library functions / methods / constants
* Common variable name constructs `*error*`, `*msg*`, `*adr* etc. so that words like `errormsg` are considered correct.

**Comment by david-fong** [comment]
I have started some work on this [here](https://github.com/david-fong/cspell-cpp).

I have a file for keywords and basic vocabulary, files for the standard library functions and constants, a file for jargon, a file for notable people in the ecosystem, keywords and names of tools in the ecosystem, and I'm working on a file for the boost library.

The repo is public domain.

Let me know if there's any way I can help integrate this work into this repo.

**Comment by Jason3S** [comment]
@david-fong,

Please feel free to make a PR updating [dictionaries/cpp](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/cpp) by adding a `src` directory and putting your files there.

**Comment by david-fong** [comment]
I feel like this issue can be closed now. @Jason3S do you think so? For anyone who finds this thread in the future, the next step right now is #1167.
